/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestionequipe.vue;

import com.gestionequipe.controleur.ServiceILocal;
import com.gestionequipe.controleur.ServiceImpl;
import com.gestionequipe.metier.Membre;
import com.gestionequipe.metier.Memtac;
import com.gestionequipe.metier.Tache;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yblad
 */
public class frmAssignerTache extends javax.swing.JInternalFrame {

    /**
     * Creates new form AssignerTache
     */
    public ServiceILocal se = new ServiceImpl();
	private  Memtac memtac=new Memtac();
	   List<Membre> listmembre=new ArrayList<>();
	 List<Tache> listache=new ArrayList<>();
         List<Memtac> listmemtac=new ArrayList<>();
	//  JComboBox<Integer> cmbMembre;
        // JComboBox<Integer> cmbTache;
    public frmAssignerTache() {
        initComponents();
    }
public void RemplirCombomembre() 
	{
		listmembre=se.GetAllMembre();
		for(Membre membre:listmembre) 
		{
		cmbMembre.addItem(membre.getMembreId());
		}
	 
	}
	public void RemplirCombotache() 
	{
		listache=se.GetAllTache();
		for(Tache tache:listache) 
		{
                cmbTache.addItem(tache.getTacheId());
		}
	 		
		
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        btnAssignerTache = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAssignerTache = new javax.swing.JTable();
        cmbMembre = new javax.swing.JComboBox<>();
        cmbTache = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("MEMBRE:");

        jLabel2.setText("TACHE:");

        jLabel3.setText("NOM:");

        jLabel4.setText("DESCRIPTION:");

        btnAssignerTache.setText("ASSIGNER TACHE");
        btnAssignerTache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignerTacheActionPerformed(evt);
            }
        });

        tbAssignerTache.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOM MEMBRE", "DESCRIPTION TACHE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbAssignerTache);

        cmbMembre.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { }));
        cmbMembre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMembreItemStateChanged(evt);
            }
        });

        cmbTache.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] {  }));
        cmbTache.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTacheItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignerTache)
                .addGap(243, 243, 243))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNom)
                            .addComponent(cmbMembre, 0, 167, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescription)
                            .addComponent(cmbTache, 0, 174, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cmbMembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(btnAssignerTache)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        ListerMembreTache();
            RemplirCombomembre() ;
            RemplirCombotache() ;
    }//GEN-LAST:event_formInternalFrameOpened
                public void ListerMembreTache()
		{	
                     //int id = new Integer(data[0]=listmemtac.get(i).getTacheID());
				Tache tach;//=se.FindOneTache(id);
			//	txtDescription.setText(tach.getTacheDescription());
		 
		 listmemtac=se.GetAllMembreTache();
		 DefaultTableModel model= (DefaultTableModel) tbAssignerTache.getModel();
			 
			 Object[]data=new Object[6] ;
                         int idT,idM,idTM;
			 for(int i=0;i<listmemtac.size();i++) 
			 {
                             
				// data[0]=listmemtac.get(i).getTacheID();
                                 idT=listmemtac.get(i).getTacheID();
				// data[1]=listmemtac.get(i).getMembreID();
                                 idM=listmemtac.get(i).getMembreID();
				// data[2]=listmemtac.get(i).getTacheID();
                                 idTM=listmemtac.get(i).getTacheID();
                                 
                                  data[0]=se.FindOneMembre(idM).getMembreNom()+"  "+se.FindOneMembre(idM).getMembrePrenom();
                                  data[1]=se.FindOneTache(idT).getTacheDescription();
                                //  data[1]=se.FindOneTache(idT);
                                 // data[2]=se.FindOneTache(idT);
                                    
				 model.addRow(data);
				 
			 }
		}
    private void btnAssignerTacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignerTacheActionPerformed
        // TODO add your handling code here:
        memtac.setMembreID((int) cmbMembre.getSelectedItem()); 
				memtac.setTacheID((int) cmbTache.getSelectedItem());
				String rep=	se.Assigner_tache(memtac);	
				if(rep=="valider")
				{
					 
                                        JOptionPane.showMessageDialog(frmAssignerTache.this, "Assigner Tache enregistre", "Information Message", 1);
				   //ClearTextField();
				}
				else
				{
					JOptionPane.showMessageDialog(frmAssignerTache.this, "Enregistrement echoue", "Information Message", 1);
					
				}
				
    }//GEN-LAST:event_btnAssignerTacheActionPerformed

    private void cmbMembreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMembreItemStateChanged
        // TODO add your handling code here:
                                int id = new Integer(cmbMembre.getSelectedItem().toString());
				Membre memb=se.FindOneMembre(id);
				txtNom.setText(memb.getMembreNom()+" "+memb.getMembrePrenom());
    }//GEN-LAST:event_cmbMembreItemStateChanged

    private void cmbTacheItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTacheItemStateChanged
        // TODO add your handling code here:
                                int id = new Integer(cmbTache.getSelectedItem().toString());
				Tache tach=se.FindOneTache(id);
				txtDescription.setText(tach.getTacheDescription());
    }//GEN-LAST:event_cmbTacheItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignerTache;
    private javax.swing.JComboBox<Integer> cmbMembre;
    private javax.swing.JComboBox<Integer> cmbTache;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAssignerTache;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
