/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestionequipe.vue;

/**
 *
 * @author yblad
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMembre = new javax.swing.JMenu();
        smnMembre = new javax.swing.JMenuItem();
        mnTache = new javax.swing.JMenu();
        smnTache = new javax.swing.JMenuItem();
        smnAssignerTache = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnMembre.setText("Membre");

        smnMembre.setText("Membre");
        smnMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnMembreActionPerformed(evt);
            }
        });
        mnMembre.add(smnMembre);

        jMenuBar1.add(mnMembre);

        mnTache.setText("Tache");

        smnTache.setText("Tache");
        smnTache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnTacheActionPerformed(evt);
            }
        });
        mnTache.add(smnTache);

        smnAssignerTache.setText("Assigner Tache");
        smnAssignerTache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnAssignerTacheActionPerformed(evt);
            }
        });
        mnTache.add(smnAssignerTache);

        jMenuBar1.add(mnTache);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnMembreActionPerformed
        // TODO add your handling code here:
        frmAjouterMembre fam=new frmAjouterMembre();
        desktop.add(fam);
        fam.show();
        
    }//GEN-LAST:event_smnMembreActionPerformed

    private void smnTacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnTacheActionPerformed
        // TODO add your handling code here:
        frmTache ft=new frmTache();
        desktop.add(ft);
        ft.show();
    }//GEN-LAST:event_smnTacheActionPerformed

    private void smnAssignerTacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnAssignerTacheActionPerformed
        // TODO add your handling code here:
        frmAssignerTache fat=new frmAssignerTache();
        desktop.add(fat);
        fat.show();
    }//GEN-LAST:event_smnAssignerTacheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnMembre;
    private javax.swing.JMenu mnTache;
    private javax.swing.JMenuItem smnAssignerTache;
    private javax.swing.JMenuItem smnMembre;
    private javax.swing.JMenuItem smnTache;
    // End of variables declaration//GEN-END:variables
}
